apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s/
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: logstash
  name: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: logstash
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s/
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: logstash
    spec:
      containers:
        - env:
            - name: LS_JAVA_OPTS
              value: -Xms512m -Xmx512m
          image: docker.elastic.co/logstash/logstash:7.17.3
          name: logstash
          ports:
            - containerPort: 5044
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/share/logstash/pipeline
              name: logstash-cm0
            - mountPath: /logs
              name: logstash-claim1
      restartPolicy: Always
      volumes:
        - configMap:
            name: logstash-cm0
          name: logstash-cm0
        - name: logstash-claim1
          persistentVolumeClaim:
            claimName: logstash-claim1
