apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s/
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: mock-kakao
  name: mock-kakao
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mock-kakao
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s/
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: mock-kakao
    spec:
      containers:
        - image: mock-kakao
          name: mock-kakao
          ports:
            - containerPort: 8081
              protocol: TCP
      restartPolicy: Always
