apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s/
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: spring-boot-app
  name: spring-boot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: spring-boot-app
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s/
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: spring-boot-app
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker,generate-users
          image: spring-boot-app
          name: spring-boot-app
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /spring-logs
              name: spring-boot-app-claim0
      restartPolicy: Always
      volumes:
        - name: spring-boot-app-claim0
          persistentVolumeClaim:
            claimName: spring-boot-app-claim0
